import Head from 'next/head'
import Body from './Components/Body'
import NavBar from './Components/NavBar'
import Portfolio from './Components/Portfolio'
import Services from './Components/Services'
import { useState } from 'react'
import Footer from './Components/Footer'


export default function Home() {
  const [DarkMode, setDarkMode]=useState(false)
  return (
    <div className={DarkMode ?"dark":""}>
      <Head>
        <title>Grace Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white pl-5 pr-2 pt-10 lg:px-40 dark:bg-gray-900'>
     <section className='min-h-screen'>
      <NavBar  DarkMode={DarkMode} setDarkMode={setDarkMode}/>
      <Body/>
      
     </section>

     <section>
      <Services/>
      <Portfolio />
      <Footer/>
     </section>
      </main>

     
    </div>
  )
}
